### ISSUE TITLE
Make App Responsive to work on Mobile Phones.

### ISSUE THREAD

**Issue by yashchaudhari008** [yashchaudhari008/drawit#1]
Currently app is clipped on mobile and toolbar is not great. I want a navbar holding all buttons and canvas to be aligned properly on mobile devices!

<img width="400px" src="https://user-images.githubusercontent.com/29065088/135754884-1e61eafd-aea1-45cc-a229-5aede305335f.png" />

**Comment by Kyaw-Min-lwin** [comment]
Can I work on this?

**Comment by yashchaudhari008** [comment]
> Can I work on this?

Sure, keep me updated.

**Comment by Kyaw-Min-lwin** [comment]
I am not sure, I am finished yet, but it looks quite responsive. Can I have your feedback on the design? Should I host the branch I am working on, so it is easier for you to review the changes?

**Comment by yashchaudhari008** [comment]
@Kyaw-Min-lwin Share the screenshot here. I will follow up👍

**Comment by Kyaw-Min-lwin** [comment]
Ok @yashchaudhari008 
![Screenshot (156)](https://user-images.githubusercontent.com/75528116/135765692-3f2be22a-2b18-4d6a-bc0f-67dcf6a56b89.png)
Would like your feedback.

**Comment by yashchaudhari008** [comment]
I am expecting something like this.
Also you can hide that instructions  "q and a to increase/decrease pen size" as they are mean only for PC users.
![](https://user-images.githubusercontent.com/29065088/135766037-9dba02e3-3d6a-4afe-ae41-7fb36461ecbe.png)

**Comment by Kyaw-Min-lwin** [comment]
Ok, thanks this makes it quite clear.

**Comment by Kyaw-Min-lwin** [comment]
Hey, how is this? @yashchaudhari008 
![Screenshot (157)](https://user-images.githubusercontent.com/75528116/135807554-6dc9ba8c-8910-45ba-badc-cf3ad1e6a5c8.png)

**Comment by yashchaudhari008** [comment]
> Hey, how is this? @yashchaudhari008 ![Screenshot (157)](https://user-images.githubusercontent.com/75528116/135807554-6dc9ba8c-8910-45ba-badc-cf3ad1e6a5c8.png)

Check https://www.w3schools.com/howto/howto_js_topnav_responsive.asp , can you make all buttons appear in dropdown when user click the button?

**Comment by Kyaw-Min-lwin** [comment]
@yashchaudhari008  Should I make it so that all of the buttons, color selection box, and the pen size only show up when the user clicks a dropdown, or is it only for the buttons.

**Comment by yashchaudhari008** [comment]
Only for buttons

**Comment by yashchaudhari008** [comment]
Also make sure that footer is visible and canvas is properly scaled on mobile displays.

**Comment by Kyaw-Min-lwin** [comment]
> Also make sure that footer is visible and canvas is properly scaled on mobile displays.

The user needs to scroll down a little for them to see the footer. 
![Screenshot (158)](https://user-images.githubusercontent.com/75528116/135828314-53e0dc9f-c73f-4f88-9374-db609bf439f6.png)
![Screenshot (159)](https://user-images.githubusercontent.com/75528116/135828336-50f7d9e2-7ec0-4eda-8a56-c4c033fa83c0.png)

**Comment by Kyaw-Min-lwin** [comment]
@yashchaudhari008 is there anyone working on this other than me. Should I be worried about the other issues(others r working on) will it affect me. Sry this is my first time contributing to open source.

**Comment by yashchaudhari008** [comment]
No need to worry.

Few Changes Required:-
1. Options button should hide on desktop.
2. Hovering over submenu should change background color (like buttons).
3. Window should fully fit on mobile screen(without any scrollbars).

**Comment by Kyaw-Min-lwin** [comment]
I have hidden the options button desktop. I also added the hover(U need to either resize the browser or the inspect bar,  using the toggle inspect toolbar doesn't show you the hover even on the color select thing.) I will need help with the third one. I can't use css because the browser is automatically applying the height n width to the canvas. This is probably due to the js.

**Comment by yashchaudhari008** [comment]
Okay, if first two changes are done you can send a PR so i can investigate further.
