### ISSUE TITLE
Redesign top Tool bar and also make it work on mobiles. 

### ISSUE THREAD

**Issue by yashchaudhari008** [yashchaudhari008/drawit#25]
Current:-
![image](https://user-images.githubusercontent.com/29065088/136690837-d0986cf5-0f5d-4e6b-b4c0-aeac5dbf68b5.png)

- Make it compact, simple
- Remove Text Hint and directly show binding on respective tool buttons
And other UI changes to make it look better.

For reference use(on mobile):- https://excalidraw.com/

**Comment by iamvaiibhav19** [comment]
@yashchaudhari008  Assign this issue to me.

**Comment by yashchaudhari008** [comment]
@pragyaSingh13 , as @iamvaiibhav19 has no updates with progress wanna take up the issue?

**Comment by yashchaudhari008** [comment]
Lets keep the app work **only on PC**. Rather than redesigning whole thing!
