### ISSUE TITLE
Display preview of actual pen size 

### ISSUE THREAD

**Issue by maskmanlucifer** [yashchaudhari008/drawit#3]
It will be good if there will be a temporary visible bubble indicating pen size on change.
For now there is only one way to know pen size after change by clicking on canvas and this is bad bcoz we dont have erase and undo functionalities till now.

**Comment by maskmanlucifer** [comment]
I can work on this issue please assign this issue to me.

**Comment by yashchaudhari008** [comment]
Please refer issue #2 .  And if it something different than that issue, please provide some sample maybe screenshot or quick diagram.

**Comment by yashchaudhari008** [comment]
Great idea, rather than 4-5 sec preview directly add preview near pen size(to the left of it.)
I will assign this issue to you.

**Comment by maskmanlucifer** [comment]
> Great idea, rather than 4-5 sec preview directly add preview near pen size(to the left of it.) I will assign this issue to you.

okk sure

**Comment by maskmanlucifer** [comment]
@yashchaudhari008 there is a problem in displaying pen size beside pen size box , since you haven't added any limit on pen size so when pen size become too large then that will be a bad ui with such big dot.
Better to show that dot in canvas bcoz we can have pretty much large space in canvas.
What do you think ???.

**Comment by yashchaudhari008** [comment]
Okay, but make sure it goes with UI.
