### ISSUE TITLE
Changing cursor icon to brush tip.

### ISSUE THREAD

**Issue by deepampriyadarshi** [yashchaudhari008/drawit#38]
## Current scenario
In the existing code the cursor is just a _simple arrow_ for the both the **drawing mode** and **erasing mode**.  Also the pointed tip of the _arrow cursor_  doesn't give the correct precision for various thickness/stroke of the brush tip. And the same _arrow cursor_ doesn't help distinguish between **drawing mode** and **erasing mode**.

## Proposed Solution
Completely replacing the cursor with a circle which will:
1. Trace the current position of mouse _in the canvas_.
2. Change it's colour according to the _stroke colour_.
3. Change it's size according to the _stoke thickness_.

**Comment by deepampriyadarshi** [comment]
Hi @yashchaudhari008 can I implement this feature?

**Comment by yashchaudhari008** [comment]
Just update me here before making an PR

**Comment by deepampriyadarshi** [comment]
> Just update me here before making an PR

## Existing feature
![old](https://user-images.githubusercontent.com/65447610/137599190-4777225b-8bd0-4536-8a72-84e15adc48fb.gif)


## Modification
![new](https://user-images.githubusercontent.com/65447610/137599205-2d6b75cf-595c-4931-9621-78f5077bf4ed.gif)

@yashchaudhari008  This is what I have been working on (The GIF uploaded above kinda looks slow).

**Comment by yashchaudhari008** [comment]
I just wanted the new cursor should be visible. Like, cursor clearly should be differentiated from canvas drawing.

**Comment by deepampriyadarshi** [comment]
> I just wanted the new cursor should be visible. Like, cursor clearly should be differentiated from canvas drawing.

## Modified.

![modified](https://user-images.githubusercontent.com/65447610/137632998-a1c33435-b824-4552-8397-f5b21f33b138.gif)

In this modification I have given a contrasting outline with respect to the colours that will be present on the canvas, to the brush tip. 

**P.S-** The thickness of the outline of the circle is included the effective painting area of the brush tip. Which means on clicking the the area enclosed in the circle + the thickness of the outline will get painted.
