### ISSUE TITLE
Update required in UI 

### ISSUE THREAD

**Issue by mukulsinghal407** [yashchaudhari008/drawit#8]
@yashchaudhri008, the project is amazing and interesting in all the fields, but required a better UI as the button size of the CTF button is way too small and the responsiveness of the index.html page is there but again the button size was a problem. I have taken the leverage to get a confirmation alert if the user clicks the "Back to home" button in main.html.

I have integrated all the changes in my fork. I would request you to see the same and inform me of any amendments.

**Comment by yashchaudhari008** [comment]
Similar Issues:- 
#1 
#2 
#3

**Comment by mukulsinghal407** [comment]
#9 Please refer to the pull request for the same.
And accept this to your beautiful model. 
Please

**Comment by mukulsinghal407** [comment]
This is actually my first open source project. Sorry for the inconvenience.

You might want to look into the interactive exit part from main.html to index.html.
Can I use bootstrap in this?

**Comment by mukulsinghal407** [comment]
@yashchaudhari008 bootstrap will make things easy and the code easier to understand, plus adding this will make a lot of things responsive by default.

**Comment by yashchaudhari008** [comment]
Yeah, but this is simple project. I don't want to add bootstrap to this project. Thanks for sharing your views👍🏼.
